# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish to Maven Central

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build
      
    - name: Copy key to tmp file
      run: 'echo "$PRIV_KEY64" > ./key64 && base64 -d ./key64 > ./key'
      shell: bash
      env:
        PRIV_KEY64: ${{ secrets.PRIV_KEY64 }}

    - name: Publish to Maven Central
      run: gradle publishAllPublicationsToSonatypeRepository
      env:
        SIGNING_KEY_ID: ${{ secrets.KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.PASSWORD }}
        SIGNING_SECRET_KEY_RING_FILE: './key'
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
